# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Utilisateurs',
                'verbose_name': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Appellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Appellations',
                'verbose_name': 'Appellation',
            },
        ),
        migrations.CreateModel(
            name='Chateau',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Chateaux',
                'verbose_name': 'Chateau',
            },
        ),
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Classements',
                'verbose_name': 'Classement',
            },
        ),
        migrations.CreateModel(
            name='Couleur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Couleurs',
                'verbose_name': 'Couleur',
            },
        ),
        migrations.CreateModel(
            name='ISWN',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iswn', models.CharField(blank=True, max_length=255, null=True)),
                ('appellation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to='api.Appellation')),
                ('chateau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='api.Chateau')),
                ('classement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                 to='api.Classement')),
                ('couleur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                              to='api.Couleur')),
            ],
            options={
                'verbose_name_plural': 'ISWN',
                'verbose_name': 'ISWN',
            },
        ),
        migrations.CreateModel(
            name='Millesime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('millesime', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Millesimes',
                'verbose_name': 'Millesime',
            },
        ),
        migrations.AddField(
            model_name='iswn',
            name='millesime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='api.Millesime'),
        ),
    ]
