version: '2'
services:
  backend:
    volumes:
      - ./backend:/backend
    environment:
      SECRET_KEY: "rwwyav18z8ipr15dvnrwwwe4kgcr7zjg"
    command: python manage.py runserver 0.0.0.0:8000
  frontend:
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    command: npm run dev
volumes:
  node_modules:
